In [191]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score , confusion_matrix
from sklearn.model_selection import train_test_split

In [192]:
df = pd.read_csv("diabetes.csv")

In [193]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [194]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [195]:
df.duplicated().sum()

np.int64(0)

In [196]:
df.shape

(768, 9)

In [197]:
x = df.drop(columns=['Outcome'], axis=1)
y = df['Outcome']

In [198]:
MMS = MinMaxScaler()
x = MMS.fit_transform(x)

### split the dataset

In [199]:
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state= 42, test_size= .1)

### Scale the data

In [200]:
MMS = MinMaxScaler()

In [201]:
# x_train_scaled = MMS.fit_transform(x_train)
# x_test_scaled = MMS.transform(x_test)


### Train and test using LogisticRegression

In [202]:
Log_Re = LogisticRegression()

In [203]:
model1 = Log_Re.fit(x_train, y_train)

In [204]:
model1.score(x_train, y_train)

0.768451519536903

In [205]:
model1.score(x_test, y_test)

0.7272727272727273

In [206]:
pred1 = model1.predict(x_test)

In [207]:
print("accuracy_score (LogisticRegression) : ", accuracy_score(pred1, y_test))

accuracy_score (LogisticRegression) :  0.7272727272727273


In [208]:
cm = confusion_matrix(y_test, pred1)

In [209]:
cm

array([[40, 10],
       [11, 16]])

In [210]:
proba = model1.predict_proba(x_test)[:,1]

In [211]:
proba

array([0.32515859, 0.19280087, 0.1470852 , 0.2891091 , 0.47310575,
       0.43029476, 0.04956625, 0.457022  , 0.50230539, 0.64760699,
       0.33512411, 0.79578718, 0.38840312, 0.35074329, 0.13585111,
       0.37003599, 0.15889814, 0.1387413 , 0.68976546, 0.41025875,
       0.25524988, 0.12446001, 0.51650665, 0.13126628, 0.53173103,
       0.77527943, 0.19577027, 0.08170533, 0.22259289, 0.18189023,
       0.70784246, 0.72375605, 0.6748839 , 0.62554999, 0.48205282,
       0.67262317, 0.87827174, 0.26446935, 0.55751075, 0.4322871 ,
       0.12647962, 0.50378877, 0.49445929, 0.41381203, 0.09433835,
       0.52225771, 0.60486625, 0.23487436, 0.45251555, 0.85919733,
       0.10277455, 0.67990193, 0.78370166, 0.2721885 , 0.1712767 ,
       0.08651761, 0.66130326, 0.03278775, 0.36513074, 0.61734358,
       0.65973419, 0.29705327, 0.39822114, 0.39296444, 0.10907383,
       0.44035615, 0.09279078, 0.55373282, 0.09595653, 0.65738666,
       0.66623256, 0.13066944, 0.28002691, 0.13533526, 0.16813

In [252]:
y_pred = (proba >= .6).astype(int)

In [253]:
accuracy_score(y_pred, y_test)

0.7662337662337663

In [254]:
confusion_matrix(y_test, y_pred)

array([[45,  5],
       [13, 14]])

### Train and test using KNN

In [255]:
Knn = KNeighborsClassifier(n_neighbors=7)

In [256]:
model2 = Knn.fit(x_train, y_train)

In [257]:
model2.score(x_train, y_train)

0.8075253256150506

In [258]:
model2.score(x_test, y_test)

0.6493506493506493

In [259]:
pred2 = model2.predict(x_test)

In [260]:
print("Accuracy Score (KNN) : ", accuracy_score(pred2, y_test))

Accuracy Score (KNN) :  0.6493506493506493
